//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

import { DateTime } from 'luxon/src/datetime';

import { CategoryDto } from '../backend/category';

/* tslint:disable */

// ReSharper disable InconsistentNaming

export interface PaginatedListOfCategoryDto {
  items: CategoryDto[];
  pageIndex: number;
  totalPages: number;
  totalCount: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}

export interface CreateCategoryCommand {
  name: string;
  description: string;
  avatar: string;
  isDefault: boolean;
}

export interface UpdateCategoryCommand {
  id: string;
  name: string;
  description: string;
  avatar: string;
  isDefault: boolean;
}

export interface LoginResponse {
  token: string;
  refreshToken: string;
}

export interface LoginCommand {
  username: string;
  password: string;
  rememberMe: boolean;
}

export interface RefreshTokenResponse {
  token: string;
  refreshToken: string;
}

export interface RefreshTokenCommand {
  token: string;
  refreshToken: string;
}

export interface RegisterUserCommand {
  username: string;
  email: string;
  password: string;
  confirmPassword: string;
}

export interface WeatherForecast {
  date: DateTime;
  temperatureC: number;
  temperatureF: number;
  summary: string | null;
}
