// Generated by Copilot
import { keys, lensProp, pipe, reduce, set } from 'ramda';

export const updatePartialObject = <T extends object>(
  target: T,
  source: Partial<T>,
): T => {
  if (
    typeof target !== 'object' ||
    target === null ||
    typeof source !== 'object' ||
    source === null
  ) {
    throw new TypeError('Both target and source must be non-null objects');
  }
  return pipe(
    (obj: Partial<T>) => keys(obj).map(String),
    reduce((acc: T, key: string) => {
      const typedKey = key as keyof T;
      const xLens = lensProp<T>(typedKey);
      return set(xLens, source[typedKey] as T[typeof typedKey], acc);
    }, target),
  )(source) as T;
};
